[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/storb"]

[workspace.package]
version = "0.1.0"
description = "An object storage subnet on the Bittensor network"
edition = "2021"
authors = ["Storb Developers"]
homepage = "https://storb.dev"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
# Storb
storb_base = { version = "*", path = "crates/storb_base" }
storb_miner = { version = "*", path = "crates/storb_miner" }
storb_validator = { version = "*", path = "crates/storb_validator" }

# Third party
anyhow = "1.0.95"
axum = { version = "0.8.1", features = ["multipart", "macros"] }
blake3 = "1.5.5"
clap = { version = "4.5.26", features = ["derive"] }
config = { version = "0.15.6", features = ["toml"] }
futures = "0.3.31"
rand = "0.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tarpc = { version = "0.35.0", features = ["full"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-serde = { version = "0.9.0", features = ["serde"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = [
    "ansi",
    "env-filter",
    "fmt",
    "registry",
    "std",
] }
uuid = "1.12.1"
rcgen = { version = "0.13.2", features = ["crypto", "pem", "ring"] }
quinn = "0.11.2"
rustls = { version = "*" }
bytes = "1.9.0"


[profile.release]
codegen-units = 1
opt-level = 2
