[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/storb"]

[workspace.package]
version = "0.1.0"
description = "An object storage subnet on the Bittensor network"
edition = "2021"
authors = ["Storb Developers"]
homepage = "https://storb.dev"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
clap = { version = "4.5.26", features = ["derive"] }
crabtensor = { version = "0.3.0", git = "https://github.com/fr34kcoders/crabtensor" }
config = { version = "0.15.6", features = ["toml"] }
serde = { version = "1.0.217", features = ["derive"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = [
    "ansi",
    "env-filter",
    "fmt",
    "registry",
    "std",
] }

[profile.release]
codegen-units = 1
opt-level = 2
