[package]
name = "storb_miner"
version = "0.1.0"
edition.workspace = true

[dependencies]
# Storb
storb_schemas.workspace = true
storb_base.workspace = true

# Third party
anyhow.workspace = true
blake3.workspace = true
capnp.workspace = true
futures.workspace = true
tarpc.workspace = true
tokio.workspace = true
tokio-serde.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
rand.workspace = true
uuid.workspace = true
