[package]
name = "storb_validator"
version = "0.1.0"
edition.workspace = true

[dependencies]
storb_base.workspace = true
storb_schemas = { path = "../../crates/storb_schemas" }
capnp = "0.20"

tokio.workspace = true
tokio-serde = { version = "0.9.0", features = ["serde"] }
tarpc = { version = "0.35.0", features = ["full"] }
futures = "0.3.31"
anyhow = "1.0.95"
