[package]
name = "storb_validator"
version = "0.1.0"
edition.workspace = true

[dependencies]
# Storb
storb_base.workspace = true
storb_schemas.workspace = true
storb_miner.workspace = true

# Third party
anyhow.workspace = true
axum.workspace = true
capnp.workspace = true
futures.workspace = true
rand.workspace = true
serde_json.workspace = true
tarpc.workspace = true
tokio.workspace = true
tokio-serde.workspace = true
tracing.workspace = true
uuid.workspace = true
