[package]
name = "storb_schemas"
version = "0.1.0"
edition.workspace = true

[dependencies]
capnp.workspace = true # Note this is a different library than capnp*c*

[build-dependencies]
capnpc = "0.20.1"
