[package]
name = "storb"
version.workspace = true
description.workspace = true
edition.workspace = true

# [lints]
# workspace = true

[[bin]]
name = "storb"
path = "src/main.rs"

[dependencies]
storb_miner.workspace = true
storb_validator.workspace = true

clap.workspace = true
config.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tarpc = { version = "0.35.0", features = ["full", "serde-transport"] }
tokio.workspace = true
tokio-serde = "0.9.0"
rcgen.workspace = true
