[package]
name = "storb"
version.workspace = true
description.workspace = true
edition.workspace = true

# [lints]
# workspace = true

[[bin]]
name = "storb"
path = "src/main.rs"

[dependencies]
clap.workspace = true
config.workspace = true
serde.workspace = true
tracing.workspace = true

