[package]
name = "storb_base"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
name = "base"

[dependencies]
crabtensor.workspace = true
dirs.workspace = true
rand.workspace = true
subxt.workspace = true
tokio.workspace = true
tracing.workspace = true
zfec-rs.workspace = true
