[package]
name = "storb_base"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
name = "neuron"

[dependencies]
crabtensor.workspace = true
dirs.workspace = true
libp2p.workspace = true
rocksdb.workspace = true
subxt.workspace = true
tokio.workspace = true
tracing.workspace = true
