name: CI
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"

env:
  ROCKSDB_LIB_DIR: /usr/lib/x86_64-linux-gnu/

jobs:
  checks:
    name: Checks for linting and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Install dependencies
        run: |
          sudo apt install librocksdb-dev

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Linting check
        run: |
          cargo clippy --workspace --all-targets --all-features -- --deny warnings
          cargo clippy --workspace --all-targets --no-default-features -- --deny warnings

      - name: Formatting check
        run: cargo fmt --check --all
